services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
  
  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
  
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
      